spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/localgems
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    locations:db/migration/postgres